name: XConomy
version: ${project.version}
main: me.yic.xconomy.XConomy
author: YiC
load: STARTUP
softdepend: [ Vault, Enterprise, DatabaseDrivers, MPoints, PlaceholderAPI ]
api-version: "1.13"

commands:
  xconomy:
    usage: /<command>
    description: XConomy.
    aliases: [ xc ]
  money:
    usage: /<command>
    description: XConomy.
  balance:
    usage: /<command>
    description: XConomy.
    aliases: [ bal ]
  balancetop:
    usage: /<command>
    description: XConomy.
    aliases: [ baltop ]
  pay:
    usage: /<command>
    description: XConomy.

permissions:
  xconomy.user.balance:
    default: true
    children:
      xconomy.user.balance.other: true
  xconomy.user.pay:
    default: true
    children:
      xconomy.user.pay.receive: true
  xconomy.user.balancetop:
    default: true
  xconomy.admin.give:
    default: op
  xconomy.admin.take:
    default: op
  xconomy.admin.set:
    default: op
  xconomy.admin.balancetop:
    default: op